USE [LawFirmDRM]
GO

/****** Object:  Table [dbo].[CASE_EXPENSE]    Script Date: 12/14/2012 09:58:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CASE_EXPENSE](
	[case_exp_ID] [int] IDENTITY(1,1) NOT NULL,
	[case_ID] [int] NOT NULL,
	[description] [nvarchar](255) NULL,
	[expense_cost] [money] NULL,
	[date] [date] NULL,
 CONSTRAINT [PK_CASE_EXP_ID] PRIMARY KEY CLUSTERED 
(
	[case_exp_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CASE_EXPENSE]  WITH CHECK ADD  CONSTRAINT [FK_CASE_ID3] FOREIGN KEY([case_ID])
REFERENCES [dbo].[COURT_CASE] ([case_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CASE_EXPENSE] CHECK CONSTRAINT [FK_CASE_ID3]
GO

