USE [LawFirmDRM]
GO

/****** Object:  Table [dbo].[CASE_EMPLOYEE]    Script Date: 9/21/2012 8:35:17 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CASE_EMPLOYEE](
	[case_ID] [int]  NOT NULL,
	[employee_ID] [int] NOT NULL,
	[employee_rate] [money] NULL,
	[START_TIME][datetime] NULL,
	[END_TIME][datetime] NULL,
	[EMPLOYEE_FIXED_COST][money] NULL
 CONSTRAINT [PK_CASE_EMP_ID] PRIMARY KEY CLUSTERED 
(
	[case_ID] ASC,
	[employee_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CASE_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_CASE_ID] FOREIGN KEY([case_ID])
REFERENCES [dbo].[COURT_CASE] ([case_ID])
GO

ALTER TABLE [dbo].[CASE_EMPLOYEE] CHECK CONSTRAINT [FK_CASE_ID]
GO

ALTER TABLE [dbo].[CASE_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_ID] FOREIGN KEY([employee_ID])
REFERENCES [dbo].[EMPLOYEES] ([employee_ID])
GO

ALTER TABLE [dbo].[CASE_EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_ID]
GO
