USE [LawFirmDRM]
GO

/****** Object:  Table [dbo].[CASE_EMPLOYEE]    Script Date: 12/13/2012 23:46:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CASE_EMPLOYEE](
	[case_emp_ID] [int] IDENTITY(1,1) NOT NULL,
	[case_ID] [int] NOT NULL,
	[employee_ID] [int] NOT NULL,
	[employee_rate] [money] NULL,
	[Description] [nvarchar](255) NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[HOURS_WORKED] [decimal](5, 2) NULL,
	[EMPLOYEE_FIXED_COST] [money] NULL,
	[CALC_TIME] [decimal](5, 2) NULL,
	[TOTAL_TIME] [decimal](5, 2) NULL,
	[e_miles] [int] NULL,
 CONSTRAINT [PK_CASE_EMP_ID] PRIMARY KEY CLUSTERED 
(
	[case_emp_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CASE_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_CASE_ID] FOREIGN KEY([case_ID])
REFERENCES [dbo].[COURT_CASE] ([case_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CASE_EMPLOYEE] CHECK CONSTRAINT [FK_CASE_ID]
GO

ALTER TABLE [dbo].[CASE_EMPLOYEE]  WITH CHECK ADD  CONSTRAINT [FK_EMPLOYEE_ID] FOREIGN KEY([employee_ID])
REFERENCES [dbo].[EMPLOYEES] ([employee_ID])
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[CASE_EMPLOYEE] CHECK CONSTRAINT [FK_EMPLOYEE_ID]
GO

