USE [LawFirmDRM]
GO

/****** Object:  Table [dbo].[CASE_EXPENSE]    Script Date: 9/21/2012 8:41:27 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CASE_EXPENSE](
	[case_ID] [int]  NOT NULL,
	[expense_type_ID] [int] NOT NULL,
	[expense_cost] [money] NULL,
 CONSTRAINT [PK_CASE_EXP_ID] PRIMARY KEY CLUSTERED 
(
	[case_ID] ASC,
	[expense_type_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CASE_EXPENSE]  WITH CHECK ADD  CONSTRAINT [FK_CASE_ID3] FOREIGN KEY([case_ID])
REFERENCES [dbo].[COURT_CASE] ([case_ID])
GO

ALTER TABLE [dbo].[CASE_EXPENSE] CHECK CONSTRAINT [FK_CASE_ID3]
GO

ALTER TABLE [dbo].[CASE_EXPENSE]  WITH CHECK ADD  CONSTRAINT [FK_EXP_TYPE_ID] FOREIGN KEY([expense_type_ID])
REFERENCES [dbo].[EXPENSE_TYPE] ([expense_type_ID])
GO

ALTER TABLE [dbo].[CASE_EXPENSE] CHECK CONSTRAINT [FK_EXP_TYPE_ID]
GO
