USE [LawFirmDRM]
GO

/****** Object:  Table [dbo].[CASE_SPECIALIST]    Script Date: 9/21/2012 8:38:22 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CASE_SPECIALIST](
	[case_ID] [int]  NOT NULL,
	[specialist_ID] [int] NOT NULL,
	[specialist_rate] [money] NULL,
	[hours][int],
	[SPECIALIST_FIXED_COST][money]
 CONSTRAINT [PK_CASE_SP_ID] PRIMARY KEY CLUSTERED 
(
	[case_ID] ASC,
	[specialist_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CASE_SPECIALIST]  WITH CHECK ADD  CONSTRAINT [FK_CASE_ID2] FOREIGN KEY([case_ID])
REFERENCES [dbo].[COURT_CASE] ([case_ID])
GO

ALTER TABLE [dbo].[CASE_SPECIALIST] CHECK CONSTRAINT [FK_CASE_ID2]
GO

ALTER TABLE [dbo].[CASE_SPECIALIST]  WITH CHECK ADD  CONSTRAINT [FK_SP_ID2] FOREIGN KEY([specialist_ID])
REFERENCES [dbo].[SPECIALISTS] ([specialist_ID])
GO

ALTER TABLE [dbo].[CASE_SPECIALIST] CHECK CONSTRAINT [FK_SP_ID2]
GO
