USE [LawFirm]
GO

/****** Object:  Table [dbo].[CLIENTS]    Script Date: 9/21/2012 8:23:26 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENTS](
	[client_ID] [int] IDENTITY(1,1) NOT NULL,
	[client_status_ID] [int] NOT NULL,
	[client_suffix_ID] [int] NOT NULL,
	[client_name] [nvarchar](255) NOT NULL,
 CONSTRAINT [PK_CLIENT_ID] PRIMARY KEY CLUSTERED 
(
	[client_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[CLIENTS]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_STATUS_ID] FOREIGN KEY([client_status_ID])
REFERENCES [dbo].[CLIENT_STATUS] ([client_status_ID])
GO

ALTER TABLE [dbo].[CLIENTS] CHECK CONSTRAINT [FK_CLIENT_STATUS_ID]
GO

ALTER TABLE [dbo].[CLIENTS]  WITH CHECK ADD  CONSTRAINT [FK_CLIENT_SUFFIX_ID] FOREIGN KEY([client_suffix_ID])
REFERENCES [dbo].[CLIENT_SUFFIX] ([client_suffix_ID])
GO

ALTER TABLE [dbo].[CLIENTS] CHECK CONSTRAINT [FK_CLIENT_SUFFIX_ID]
GO
