USE [LawFirmDRM]
GO

/****** Object:  Table [dbo].[CLIENT_RELATIONSHIP]    Script Date: 10/8/2012 12:02:25 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENT_RELATIONSHIP](
	[CLIENT_RELA_ID] [int] IDENTITY(1,1) NOT NULL,
	[CLIENT_RELATIONSHIP] [nvarchar](255) NULL,
 CONSTRAINT [PK_CLIENT_RELA_ID] PRIMARY KEY CLUSTERED 
(
	[CLIENT_RELA_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


