USE [LawFirm]
GO

/****** Object:  Table [dbo].[CLIENT_STATUS]    Script Date: 9/21/2012 8:13:28 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[CLIENT_STATUS](
	[client_status_ID] [int] IDENTITY(1,1) NOT NULL,
	[client_status] [nvarchar](25) NOT NULL,
 CONSTRAINT [PK_CLIENT_STATUS_ID] PRIMARY KEY CLUSTERED 
(
	[client_status_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


