USE [LawFirm]
GO

/****** Object:  Table [dbo].[SPECIALISTS]    Script Date: 9/21/2012 8:33:59 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SPECIALISTS](
	[specialist_ID] [int] IDENTITY(1,1) NOT NULL,
	[specialist_type_ID] [int] NULL,
 CONSTRAINT [PK_SP_ID] PRIMARY KEY CLUSTERED 
(
	[specialist_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SPECIALISTS]  WITH CHECK ADD  CONSTRAINT [FK_SP_TYPE_ID] FOREIGN KEY([specialist_type_ID])
REFERENCES [dbo].[SPECIALIST_TYPE] ([specialist_type_ID])
GO

ALTER TABLE [dbo].[SPECIALISTS] CHECK CONSTRAINT [FK_SP_TYPE_ID]
GO
